/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-10-14 09:29:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.shashi.service.impl.*;
import com.shashi.service.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1728897047878L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1728790573000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(5);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.shashi.service.impl");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.shashi.service");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #E6F9E6; /* Light green background color */\r\n");
      out.write("        background-image: url('images/3094352.jpg'); /* Path to your background image */\r\n");
      out.write("        background-size: cover; /* Ensure the image covers the entire background */\r\n");
      out.write("        background-repeat: no-repeat; /* Prevent the image from repeating */\r\n");
      out.write("        background-attachment: fixed; /* Keep the background image fixed during scrolling */\r\n");
      out.write("        background-position: center center; /* Center the background image */\r\n");
      out.write("        font-family: Arial, sans-serif; /* Default font */\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-container {\r\n");
      out.write("        border: 2px solid #4CAF50; /* Green border */\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        background-color: #FFFFFF; /* Light peach background */\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        margin: 50px auto;\r\n");
      out.write("        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("    .form-container h2 {\r\n");
      out.write("        color: #4CAF50; /* Green color for the title */\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-group {\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-group label {\r\n");
      out.write("        color: #333; /* Dark gray for labels */\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .form-group input,\r\n");
      out.write("    .form-group select {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .text-center {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-success {\r\n");
      out.write("        background-color: #FF1493; /* Magenta button */\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-success:hover {\r\n");
      out.write("        background-color: #E0148B; /* Slightly darker magenta on hover */\r\n");
      out.write("    }\r\n");
      out.write("    p {\r\n");
      out.write("        color: blue;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Logout Header</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\r\n");
      out.write("    <!--Company Header Starting-->\r\n");
      out.write("    <div class=\"container-fluid text-center\"\r\n");
      out.write("        style=\"margin-top: 55px; background-color: #12151e; color: white; padding: 5px; background-image: url('C:\\Users\\shash\\Downloads\\shopping-cart\\WebContent\\images\\header.jpg'); background-size: cover; background-position: center;\">\r\n");
      out.write("        <h2>Big Mart</h2>\r\n");
      out.write("        <h6>We specialize in Electronics of top Notch Quality</h6>\r\n");
      out.write("        <p align=\"center\" style=\"color: blue; font-weight: bold; margin-top: 5px; margin-bottom: 5px;\" id=\"message\"></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Company Header Ending-->\r\n");
      out.write("\r\n");
      out.write("    ");

    /* Checking the user credentials */
    String userType = (String) session.getAttribute("usertype");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--Starting Navigation Bar-->\r\n");
      out.write("    <nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.jsp\"><span class=\"glyphicon glyphicon-home\" style=\"color:e9d7d2;\">&nbsp;</span>Biggy Techs</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                    <!-- Search Form -->\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <form class=\"navbar-form navbar-left\" action=\"Product.jsp\" method=\"get\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"search\" placeholder=\"Search Products\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-default\">Search</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (userType == null) { 
      out.write("\r\n");
      out.write("                        <!-- Navigation links for non-logged-in users -->\r\n");
      out.write("                        <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("                        <li><a href=\"register.jsp\">Sign Up</a></li>\r\n");
      out.write("                        <li><a href=\"Product.jsp\">Products</a></li>\r\n");
      out.write("                        <li class=\"dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Services <span class=\"caret\"></span></a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a href=\"Recharge.jsp\">Recharge</a></li>\r\n");
      out.write("                                <li><a href=\"Electric.jsp\">Electricity Bill Payment</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    ");
 } else if ("customer".equalsIgnoreCase(userType)) { 
      out.write("\r\n");
      out.write("                        <!-- Navigation links for customers -->\r\n");
      out.write("                        ");

                        int notf = new CartServiceImpl().getCartCount((String) session.getAttribute("username"));
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"Product.jsp\"><span class=\"glyphicon glyphicon-home\">Products</span></a></li>\r\n");
      out.write("                        ");

                        if (notf == 0) {
                        
      out.write("\r\n");
      out.write("                            <li><a href=\"cartDetails.jsp\"> <span class=\"glyphicon glyphicon-shopping-cart\"></span>Cart</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"cartDetails.jsp\" style=\"margin: 0px; padding: 0px;\" id=\"mycart\"><i data-count=\"");
      out.print(notf);
      out.write("\" class=\"fa fa-shopping-cart fa-3x icon-white badge\" style=\"background-color: #333; margin: 0px; padding: 0px; padding-bottom: 0px; padding-top: 5px;\"></i></a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <li><a href=\"orderDetails.jsp\">Orders</a></li>\r\n");
      out.write("                        <li><a href=\"userProfile.jsp\">Profile</a></li>\r\n");
      out.write("                        <li><a href=\"cartDetails.jsp\">Cart</a></li>\r\n");
      out.write("                        <li><a href=\"./LogoutSrv\">Logout</a></li>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <!-- Navigation links for admins -->\r\n");
      out.write("                        <li><a href=\"adminViewProduct.jsp\">Products</a></li>\r\n");
      out.write("                        <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Category <span class=\"caret\"></span></a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a href=\"adminViewProduct.jsp?type=mobile\">Mobiles</a></li>\r\n");
      out.write("                                <li><a href=\"adminViewProduct.jsp?type=tv\">Tvs</a></li>\r\n");
      out.write("                                <li><a href=\"adminViewProduct.jsp?type=laptop\">Laptops</a></li>\r\n");
      out.write("                                <li><a href=\"adminViewProduct.jsp?type=camera\">Camera</a></li>\r\n");
      out.write("                                <li><a href=\"adminViewProduct.jsp?type=speaker\">Speakers</a></li>\r\n");
      out.write("                                <li><a href=\"adminViewProduct.jsp?type=tablet\">Tablets</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"adminStock.jsp\">Stock</a></li>\r\n");
      out.write("                        <li><a href=\"shippedItems.jsp\">Shipped</a></li>\r\n");
      out.write("                        <li><a href=\"unshippedItems.jsp\">Orders</a></li>\r\n");
      out.write("                        <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Update Items <span class=\"caret\"></span></a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a href=\"addProduct.jsp\">Add Product</a></li>\r\n");
      out.write("                                <li><a href=\"removeProduct.jsp\">Remove Product</a></li>\r\n");
      out.write("                                <li><a href=\"updateProductById.jsp\">Update Product</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"./LogoutSrv\">Logout</a></li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!--End of Navigation Bar-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    String message = request.getParameter("message");
    
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"form-container\">\r\n");
      out.write("            <h2>Login Form</h2>\r\n");
      out.write("            ");

            if (message != null) {
            
      out.write("\r\n");
      out.write("            <p>");
      out.print(message);
      out.write("</p>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("            <form action=\"./LoginSrv\" method=\"post\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"username\">Username</label> \r\n");
      out.write("                    <input type=\"email\" placeholder=\"Enter Username\" name=\"username\" id=\"username\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"password\">Password</label> \r\n");
      out.write("                    <input type=\"password\" placeholder=\"Enter Password\" name=\"password\" id=\"password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"userrole\">Login As</label> \r\n");
      out.write("                    <select name=\"usertype\" id=\"userrole\" required>\r\n");
      out.write("                        <option value=\"customer\" selected>CUSTOMER</option>\r\n");
      out.write("                        <option value=\"admin\">ADMIN</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn-success\">Login</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Shopping Center</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/* Global Styles */\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial, sans-serif;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  background-color: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Footer Styles */\r\n");
      out.write(".footer {\r\n");
      out.write("  background-color: #0D0D0D;\r\n");
      out.write("  color: rgb(255, 255, 255);\r\n");
      out.write("  padding: 40px 20px;\r\n");
      out.write("  margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer h3 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  color: #e0f7fa;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer p {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer p em {\r\n");
      out.write("  display: block;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Contact Information Styles */\r\n");
      out.write(".contact-info {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info div {\r\n");
      out.write("  margin: 0 15px;\r\n");
      out.write("  max-width: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info p {\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info .glyphicon {\r\n");
      out.write("  margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Form Styles */\r\n");
      out.write(".contact-form {\r\n");
      out.write("  max-width: 600px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form .form-group {\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form .form-control {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  margin: 5px 0;\r\n");
      out.write("  border: 2px solid #004d00;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form button {\r\n");
      out.write("  background-color: #004d00;\r\n");
      out.write("  color: white;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-form button:hover {\r\n");
      out.write("  background-color: #003300;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Styles */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .footer {\r\n");
      out.write("    padding: 20px 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .contact-info {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .contact-info div {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .contact-form {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Start the footer Contacts -->\r\n");
      out.write("  <div class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h3>Contact Us</h3>\r\n");
      out.write("      <p><em>Love To All Customers!</em></p>\r\n");
      out.write("      <div class=\"contact-info\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <p>Drop a note.</p>\r\n");
      out.write("          <p><span class=\"glyphicon glyphicon-map-marker\">Name:</span></p>\r\n");
      out.write("          <p><span class=\"glyphicon glyphicon-phone\"></span>Phone:</p>\r\n");
      out.write("          <p><span class=\"glyphicon glyphicon-envelope\"></span>Email: </p>\r\n");
      out.write("          <p><span class=\"glyphicon glyphicon-copyright-mark\"></span> Big Mart 2024.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contact-form\">\r\n");
      out.write("          <form action=\"fansMessage\" method=\"post\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input class=\"form-control\" id=\"name\" name=\"name\" placeholder=\"Name\" type=\"text\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email\" type=\"email\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <textarea class=\"form-control\" id=\"comments\" name=\"comments\" placeholder=\"Comment\" rows=\"5\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <button type=\"submit\">Send</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- End of Contact or About Us -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
